---
title: AED Sim
output:
  html_document: default
  word_document: default
header-includes: \usepackage{docmute,amsmath}  
---

```{r,echo=FALSE,message=FALSE,warning=FALSE}
library(knitr)
source("01_AdaptiveTrialDesign.r")


d_S0_T0 <- rbind(c('d_S0'=.12, 'd_T0'=.1), 
                 c(.15, .12))

n_2  <- 60    # one arm (rr=1:1)
cli_S0 <- .15 # bar for clin significance at read out for S
cli_F0 <- .15 # bar for clin significance at read out for F

prev_S <- .47

delta_T_S <- rbind(c('delta_S'=0.2, 'delta_T'=0.2),
                   c(0.2, 0.12),
                   c(0.2, 0.04))
rownames(delta_T_S) <- c('Weak', 'Strong', 'VeryStrong')

```


```{r,echo=FALSE,message=FALSE,warning=FALSE}
set.seed(35)
B <- 1e5#4e4

if (!file.exists('simres.rdata')) {
  res <- list()
  id <- 1
  for (id1 in 1:nrow(d_S0_T0)) {
    d_S0 <- d_S0_T0[id1, 1]
    d_T0 <- d_S0_T0[id1, 2]
    
    for (r_id in 1:nrow(delta_T_S)) {
      delta_S <- delta_T_S[r_id, 1]
      delta_T <- delta_T_S[r_id, 2]

      set.seed(35)
      res[[id]] <- AdaptiveTrialDesign(delta_S=delta_S, delta_T=delta_T, 
                                       d_S = d_S0, d_T=d_T0, nSimul = B, 
                                       cli_rev_S = cli_S0, cli_rev_F=cli_F0, n_2=n_2)
      attr(res[[id]], 'delta_S') <- delta_S
      attr(res[[id]], 'delta_T') <- delta_T
      attr(res[[id]], 'd_S0') <- d_S0
      attr(res[[id]], 'd_T0') <- d_T0
      
      id <- id+1
    } # end of for (r_id in 1:nrow(deta_T_S))    
  } # end of for (id1 in 1:nrow(d_S0_T0))

  save(res, file = 'simres.rdata')
} else {
  load('simres.rdata')
}
```

```{r,echo=F,message=F,warning=F, results='asis'}
out_tab <- list()

for (r_id in 1:length(res)) {
  out_tab[[r_id]] <- list()
  
  delta_S <- attr(res[[r_id]], 'delta_S')
  delta_T <- attr(res[[r_id]], 'delta_T')
  delta_F <- delta_S * prev_S + delta_T * (1-prev_S)
  
  d_S0 <- attr(res[[r_id]], 'd_S0')
  d_T0 <- attr(res[[r_id]], 'd_T0')

  tmp <- res[[r_id]]
  
  cat('\n\n')
  cat(paste0('### Protocol assumptions:', ' $\\Delta_S=', delta_S, 
             '$, $\\Delta_{S^c}=', delta_T, '$', ' $d_S=', d_S0, 
             '$, $d_T=', d_T0, '$'))
  cat('\n\n')
  
  ### Decision frequency
  out_tab[[r_id]]$dec_freq_tab <- dec_freq_tab <- prop.table(table(tmp$stage1_decision_detail))
  kable(dec_freq_tab, digits=3, col.names=c("Outcome","Rel. frequency"), caption = 'Decision Freq.') %>% print
  cat('\n\n')

  
  ### Power
  out_tab[[r_id]]$power_tab <- 
  power_tab <- c("Power F"=mean(tmp$signif_F),"Power S"=mean(tmp$signif_S),
                 "Power (F or S)"=mean(tmp$signif_F_or_S),"Power (F and S)"=mean(tmp$signif_F_and_S))
  kable(power_tab,digits=3,col.names=c("Power"), caption='Power') %>% print
  cat('\n\n')
  
  ### Conditional power
  
  go_power_tab <- c("CP F if only F included in stage 2"=mean(tmp$signif_F[tmp$stage1_decision%in%c('4- Continue to stage 2: F only')]),
                    
                    "CP S if only S included in stage 2"=mean(tmp$signif_S[tmp$stage1_decision%in%c('3- Continue to stage 2: S only')]),
                    
                    "CP (F or S) if F and S continue to stage 2"=mean(tmp$signif_F_or_S[tmp$stage1_decision%in%c('5- Continue to stage 2: F and S')])
                    )  
  kable(go_power_tab,digits=2,col.names=c("Conditional Power"), caption='Conditional Power') %>% print
  cat('\n\n')
  
  ### Stat & Clin Sig
  out_tab[[r_id]]$stat_clin_sig_tab <- 
  stat_clin_sig_tab <- c("Stat & Clin Sign F"=mean(tmp$signif_clinrev_F),
          "Stat & Clin Sign S"=mean(tmp$signif_clinrev_S),
          "Stat & Clin Sign (F or S)"=mean(tmp$signif_clinrev_F_or_S),
          "Stat & Clin Sign (F and S)"=mean(tmp$signif_clinrev_F_and_S))
  kable(stat_clin_sig_tab,digits=3,col.names=c("Prob."), caption='Stat & Clin Sig') %>% print  
  cat('\n\n')
  
  ### Obs effect and bias when sig.
  out_tab[[r_id]]$avg_bias_sig <- c("Bias in $\\Delta_F$ for all decisions"=(tmp$effect_F_overall[tmp$signif_F] %>% mean)-delta_F,
                                    "Bias in $\\Delta_S$ for all decisions"=(tmp$effect_S_overall[tmp$signif_S] %>% mean)-delta_S,
                                    
                                    "Bias in $\\Delta_F$ for efficacy stop at St. 1"=(tmp$effect_F_overall[tmp$signif_F & tmp$stage1_decision=='1 - Stop after stage 1: efficacy'] %>% mean)-delta_F,
                                    "Bias in $\\Delta_S$ for efficacy stop at St. 1"=(tmp$effect_S_overall[tmp$signif_S & tmp$stage1_decision=='1 - Stop after stage 1: efficacy'] %>% mean)-delta_S,
                                    
                                    "Bias in $\\Delta_F$ if only F incl. in St. 2"=(tmp$effect_F_overall[tmp$signif_F & tmp$stage1_decision=='4- Continue to stage 2: F only'] %>% mean)-delta_F,
                                    "Bias in $\\Delta_S$ if only S incl. in St. 2"=(tmp$effect_S_overall[tmp$signif_S & tmp$stage1_decision=='3- Continue to stage 2: S only'] %>% mean)-delta_S, 
                                    
                                    "Bias in $\\Delta_F$ if F and S incl. in St. 2"=(tmp$effect_F_overall[tmp$signif_F & tmp$stage1_decision=='5- Continue to stage 2: F and S'] %>% mean)-delta_F,
                                    "Bias in $\\Delta_S$ if F and S incl. in St. 2"=(tmp$effect_S_overall[tmp$signif_S & tmp$stage1_decision=='5- Continue to stage 2: F and S'] %>% mean)-delta_S) 
  
  
  ### Obs effect and bias regardless of statistical significance
  out_tab[[r_id]]$avg_bias <- c("Bias in $\\Delta_F$ for all decisions"=(tmp$effect_F_overall %>% mean)-delta_F,
                                "Bias in $\\Delta_S$ for all decisions"=(tmp$effect_S_overall %>% mean)-delta_S,
                                    
                                    "Bias in $\\Delta_F$ for efficacy stop at St. 1"=(tmp$effect_F_overall[tmp$stage1_decision=='1 - Stop after stage 1: efficacy'] %>% mean)-delta_F,
                                    "Bias in $\\Delta_S$ for efficacy stop at St. 1"=(tmp$effect_S_overall[tmp$stage1_decision=='1 - Stop after stage 1: efficacy'] %>% mean)-delta_S,
                                    
                                    "Bias in $\\Delta_F$ if only F incl. in St. 2"=(tmp$effect_F_overall[tmp$stage1_decision=='4- Continue to stage 2: F only'] %>% mean)-delta_F,
                                    "Bias in $\\Delta_S$ if only S incl. in St. 2"=(tmp$effect_S_overall[tmp$stage1_decision=='3- Continue to stage 2: S only'] %>% mean)-delta_S, 
                                    
                                    "Bias in $\\Delta_F$ if F and S incl. in St. 2"=(tmp$effect_F_overall[tmp$stage1_decision=='5- Continue to stage 2: F and S'] %>% mean)-delta_F,
                                    "Bias in $\\Delta_S$ if F and S incl. in St. 2"=(tmp$effect_S_overall[tmp$stage1_decision=='5- Continue to stage 2: F and S'] %>% mean)-delta_S)   
} # end of for (r_id in 1:length(res))

```


